// @codekit-prepend 'lib/jquery-1.8.2.min.js'
// @codekit-prepend 'lib/recorderjs/recorder.js'
// @codekit-prepend 'lib/tuna/tuna.js'
// @codekit-prepend 'lib/jasmid/stream.js'
// @codekit-prepend 'lib/jasmid/midifile.js'